server.port=8888
server.servlet.contextPath=/MSGenerator

app.rootFolders=domain,mapper,service, web actions

app.kiekerLogFileLocation=C:/Development/MSGeneratorInputOutput/Input/roller

app.patternMinningAlgorithm=PrefixSpan
app.patternMinningMinimumSupport=25%

app.patternMinningLibrary=C:/Development/MSGeneratorSupportWork/spmf.jar
app.patternMinningInputFile=C:/Development/MSGeneratorInputOutput/Output/roller/A2/eventsFromLog.txt
app.patternMinningOutputFile=C:/Development/MSGeneratorInputOutput/Output/roller/A2/patternMinninglibraryOutput.txt

app.isXESFileRequired=false
app.xesFileLocation=C:/Development/MSGeneratorInputOutput/Output/roller/A2/eventsXES.xes
app.isMethodToIdMappingRequired=true
app.methodToIdMappingFile=C:/Development/MSGeneratorInputOutput/Output/roller/A2/methodToIdEventMapping.txt
# below patterns avoided in JForum.
# app.stringsToAvoidFromPatternMatching=.init,.lambda,.set,getBotAgents,WebRequestContext,CsrfFilter,CsrfHttpServletRequestWrapper,net.jforum.JForum.,net.jforum.Command.,ControllerUtils

# below patterns avoided in Apache Roller.
app.stringsToAvoidFromPatternMatching=.release(),.doFilter(,ThreadManagerImpl,.RequestMappingFilter.,.util.cache.,.pojos.,.ui.struts2.,.RollerSession,.MenuTab,<init>,ParsedTab,ParsedMenu,.menu.Menu.,.getEntityManager(,.getThreadLocalEntityManager(,WebloggerFactory.getWeblogger(,.GuiceWebloggerProvider.getWeblogger(,.JPAPersistenceStrategy.isTransactionActive(,.JPAPersistenceStrategy.load(,WebloggerFactory.isBootstrapped(),WebloggerImpl.,JPAPersistenceStrategy.getNamedQuery(,JPAPersistenceStrategy.getDynamicQuery(
app.patternCostInfoFile=C:/Development/MSGeneratorInputOutput/Output/roller/A2/patternCostInfo.txt
app.excelFileLocation=C:/Development/MSGeneratorInputOutput/Output/roller/A2/patternOutputA2.xlsx